[build]
  builder = "NIXPACKS"

[deploy]
  numReplicas = 1
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[disks]
  data = { size = "1GB", mountPoint = "/data" }

[environment]
  RAILWAY_PRIVATE_DIR = "/data"
